import {
  Alert,
  Box,
  Button,
  Checkbox,
  Column,
  Dropdown,
  Flex,
  Grid,
  // GridChoiceCell,
  Heading,
  Icon,
  Image,
  // Math,
  Modal,
  MultipleSelect,
  Option,
  Paragraph,
  Placeholder,
  QuestionButton,
  RadioButton,
  ScrollButton,
  SingleSelect,
  SingleSelectChoice,
  Slider,
  Stack,
  Stem,
  SVG,
  Tabs,
  Tag,
  Text,
  TextInput,
  Zones,
  ZonesBackground,
  Zone,
} from '@coreym/benchmark';

export const WidgetMap = {
  Alert: Alert,
  Box: Box,
  Button: Button,
  Checkbox: Checkbox,
  Column: Column,
  Dropdown: Dropdown,
  Flex: Flex,
  Grid: Grid,
  // GridChoiceCell: GridChoiceCell,
  Heading: Heading,
  Icon: Icon,
  Image: Image,
  // Math: Math,
  Modal: Modal,
  MultipleSelect: MultipleSelect,
  Option: Option,
  Paragraph: Paragraph,
  Placeholder: Placeholder,
  QuestionButton: QuestionButton,
  RadioButton: RadioButton,
  ScrollButton: ScrollButton,
  SingleSelect: SingleSelect,
  SingleSelectChoice: SingleSelectChoice,
  Slider: Slider,
  Stack: Stack,
  Stem: Stem,
  Svg: SVG,
  Tabs: Tabs,
  Tag: Tag,
  Text: Text,
  TextInput: TextInput,
  Zones: Zones,
  ZonesBackground: ZonesBackground,
  Zone: Zone,
};
