import Components from '../../components/benchmark';
export const WidgetMap = {
  Alert: Components.Alert,
  Box: Components.Box,
  Button: Components.Button,
  Checkbox: Components.Checkbox,
  ClearAnswer: Components.ClearAnswer,
  Columns: Components.Columns,
  Column: Components.Column,
  Dialog: Components.Dialog,
  Dropdown: Components.Dropdown,
  Flex: Components.Flex,
  Grid: Components.Grid,
  // GridChoiceCell: Components.GridChoiceCell,
  Heading: Components.Heading,
  Icon: Components.Icon,
  Image: Components.Image,
  Math: Components.Math,
  List: Components.List,
  ListItem: Components.ListItem,
  ListOfUnansweredItems: Components.ListOfUnansweredItems,
  OpenTimeLeftDialogButton: 'opentimeleftdialogbutton', // 'Components.OpenTimeLeftDialogButton',
  Modal: Components.Modal,
  MultipleSelect: Components.MultipleSelect,
  MultipleSelectChoice: Components.MultipleSelectChoice,
  Option: Components.Option,
  Paragraph: Components.Paragraph,
  Placeholder: Components.Placeholder,
  QuestionButton: Components.QuestionButton,
  RadioButton: Components.RadioButton,
  ScrollButton: Components.ScrollButton,
  SingleSelect: Components.SingleSelect,
  SingleSelectChoice: Components.SingleSelectChoice,
  'SingleSelect.Choice': Components.SingleSelect.Choice,
  Slider: Components.Slider,
  Stack: Components.Stack,
  Stem: Components.Stem,
  Svg: Components.SVG,
  Tabs: Components.Tabs,
  Table: Components.Table,
  TableBody: Components.TableBody,
  TableCell: Components.TableCell,
  TableCaption: Components.TableCaption,
  TableHead: Components.TableHead,
  TableHeader: Components.TableHeader,
  TableRow: Components.TableRow,
  Tag: Components.Tag,
  Text: Components.Text,
  TextInput: Components.TextInput,
  TimeLeft: Components.TimeLeft,
  Toolbar: Components.Toolbar,
  Zones: Components.Zones,
  ZonesBackground: Components.ZonesBackground,
  Zone: Components.Zone,
};
